apiVersion : v1
kind: Pod
metadata:
  name: nginx
  labels:
    env : test
    app : main
    owner : mrivich
spec:
  containers:
    - name : container-nginx
      image: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:latest
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRES_DB
      value: mydatabase
    - name: POSTGRES_USER
      value: myuser
    - name: POSTGRES_PASSWORD
      value: mypassword
    volumeMounts:
    - name: postgres-storage
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgres-storage
    emptyDir: {}
