apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test
  labels:
    app: pop
spec:
  selector:
    matchLabels:
      project: konf
  template:
    metadata:
      labels:
        project: konf
    spec:
      containers:
        - name: nginx
          image: nginx/ngnix:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-test
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
